### ISSUE TITLE
Saving breaks tracks

### ISSUE THREAD

**Issue by kevansevans** [kevansevans/openLR#1]
Loading works but saving causes lines to be ordered incorrectly. Need to find source of incorrect indexing and fix it. Once a track is saved, the break no longer occurs afaik.

**Comment by kevansevans** [comment]
Can confirm save order is not the culprit.

**Comment by kevansevans** [comment]
Issue might be only occurring when red lines are involved.

**Comment by kevansevans** [comment]
Saving and loading will be overhauled in the future

**Comment by Xeddius** [comment]
Can confirm, tracks that work before save and then loaded at a later time no longer function properly. momentum of the rider is altered mid-track.

**Comment by kevansevans** [comment]
Issue has been found to be Haxe's Float to String conversion. Saving to a .json file will cause loss of precision for line positions. Due to the nature of the physics engine, saving to any string based format is not a viable option unless Haxe offers a solution to this.

Designing a new save format is now under consideration, albeit heavily undesirable. Will leave issue open until further notice.

**Comment by kevansevans** [comment]
A fix for this issue has been found and has been applied: https://github.com/kevansevans/openLR/commit/1c46c4a65cf2cecbf1be06b047814da21debec88
