### ISSUE TITLE
Include project name in release downloads

### ISSUE THREAD

**Issue by Yepoleb** [kevansevans/openLR#6]
Using only the version number makes the files hard to find in your downloads folder. I'd suggest something like `<application>-<version>-<os>.<ext>`, which I've found the most convenient format so far. Underscore as a separator works too, but doesn't look as nice IMO.

**Comment by kevansevans** [comment]
I can do that, thanks for the advice

**Comment by kevansevans** [comment]
0.0.4 names have been updated.

**Comment by Yepoleb** [comment]
Damn, that was crazy fast.

**Comment by kevansevans** [comment]
I like to be transparent with my projects, especially something as simple as this.
