### ISSUE TITLE
not sure if issue, or if i'm doing something wrong.

### ISSUE THREAD

**Issue by jdroo** [kevansevans/openLR#8]
when ever i compile it following your instructions.

I get an output like this:
![c39c68ba7ffd5e02524312136ff7abf7](https://user-images.githubusercontent.com/13055804/31903064-378f6ad0-b7e4-11e7-9427-a4449b746517.png)

**Comment by kevansevans** [comment]
Flash deployment is unstable right now, your other options are CPP and HTML5.

**Comment by jdroo** [comment]
is there a way to compile it into an exe?

**Comment by kevansevans** [comment]
``openfl build cpp``

If that is throwing errors, run the command ``lime setup windows`` and follow the instructions it provides.

**Comment by kevansevans** [comment]
``openfl build cpp``

If that is throwing errors, run the command ``lime setup windows`` and follow the instructions it provides.
